@startuml

interface Motherboard 

Motherboard o-- Processor
Motherboard o-- Bios
Motherboard o-- SataComponent
Motherboard o-- PcieComponent
Motherboard o-- Ram

interface Processor
interface Bios
interface Cooler
interface Ram
interface XMP

interface PcieComponent
interface GraphicsCard implements PcieComponent
interface WifiCard implements PcieComponent
interface SSD implements PcieComponent


interface SataComponent
interface HDD implements SataComponent
interface OpticalDrive implements SataComponent

interface Frame
interface PSU
interface WifiCard
class Validator

@enduml